disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- multiple_closures_with_trailing_closure
- function_body_length

included:
excluded:
- Pods
- QuizCard/SceneDelegate.swift
- QuizCard/AppDelegate.swift
